In [26]:
import numpy as np

In [28]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

## Array Creation

#### np.array function is used to create numpy array from iterable objects

In [158]:
arr = [1,2,3,4]

In [163]:
np.array(arr)

array([1, 2, 3, 4])

In [164]:
np.array(arr, ndmin=6)

array([[[[[[1, 2, 3, 4]]]]]])

In [165]:
matrix = [[1,2,3],[1,2,3],[1,2,3]]

In [175]:
np.array(matrix, ndmin=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### dtype attribute is used to change the type of the array

In [177]:
np.array([0,1,2,3], dtype=bool)

array([False,  True,  True,  True])

In [201]:
np.array([0,1,2,255], dtype=np.int8)

array([ 0,  1,  2, -1], dtype=int8)

In [204]:
np.array([0,1,2,3], dtype=np.complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

In [206]:
np.array([0,1,2,3], dtype=np.float)

array([0., 1., 2., 3.])

#### Structured array can be created by specifying dtype

In [248]:
d = [('cat', 5), ('dog', 20)]

In [253]:
arr = np.array([('cat', 5), ('dog', 20)], dtype=[('name', np.object), ('age',np.int)])

In [258]:
arr['age']

array([ 5, 20])

In [259]:
arr['name']

array(['cat', 'dog'], dtype=object)

In [289]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [290]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [291]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [292]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [304]:
np.full(shape=(3,3), fill_value=2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [306]:
np.full(shape=(3,3), fill_value=['a','b','c'])

array([['a', 'b', 'c'],
       ['a', 'b', 'c'],
       ['a', 'b', 'c']], dtype='<U1')

In [312]:
np.empty((2,2))

array([[1.08482405e-311, 1.08484865e-311],
       [1.08484865e-311, 1.08484865e-311]])

In [315]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [316]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [339]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [338]:
np.linspace(1,2,5, retstep=True)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [322]:
np.linspace(2,3,5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [321]:
np.linspace(2,3,5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [331]:
np.linspace([1,2],[2,3], 5)

array([[1.  , 2.  ],
       [1.25, 2.25],
       [1.5 , 2.5 ],
       [1.75, 2.75],
       [2.  , 3.  ]])

In [332]:
np.linspace([1,2,3],[4,5,10], 5)

array([[ 1.  ,  2.  ,  3.  ],
       [ 1.75,  2.75,  4.75],
       [ 2.5 ,  3.5 ,  6.5 ],
       [ 3.25,  4.25,  8.25],
       [ 4.  ,  5.  , 10.  ]])

In [335]:
np.linspace([1,2],[4,5], 5, axis = 0)

array([[1.  , 2.  ],
       [1.75, 2.75],
       [2.5 , 3.5 ],
       [3.25, 4.25],
       [4.  , 5.  ]])

In [336]:
np.linspace([1,2],[4,5], 5, axis = 1)

array([[1.  , 1.75, 2.5 , 3.25, 4.  ],
       [2.  , 2.75, 3.5 , 4.25, 5.  ]])

In [494]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [340]:
arr = [1,2,3]

In [341]:
np.zeros_like(arr)

array([0, 0, 0])

In [351]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [350]:
np.ones_like(arr)

array([1, 1, 1, 1])

Printing normal array vs numoy array

In [354]:
arr = [1,2,3,4,5]
arr1 = [[1,2,3],[4,5,6],[7,8,9]]

In [360]:
print(arr)
print()
print(arr1)

[1, 2, 3]

[[1, 2, 3], [4, 5, 6]]


In [359]:
print(np.array(arr))
print()
print(np.array(arr1))

[1 2 3]

[[1 2 3]
 [4 5 6]]


Basic Operations

In [367]:
a = [1,2,3,4]
b = [5,6,7,8]

In [368]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [370]:
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [372]:
a = np.array(a)
b = np.array(b)
print(a,b)

[1 2 3 4] [5 6 7 8]


In [373]:
a+b

array([ 6,  8, 10, 12])

In [374]:
a-b

array([-4, -4, -4, -4])

In [375]:
a*b

array([ 5, 12, 21, 32])

In [379]:
a<=2

array([ True,  True, False, False])

In [382]:
b//2

array([2, 3, 3, 4], dtype=int32)

arithmatic assignment operator

In [383]:
a = np.array(a)
b = np.array(b)
print(a,b)

[1 2 3 4] [5 6 7 8]


In [384]:
a += b

In [386]:
print(a)

[ 6  8 10 12]


In [398]:
a = np.arange(4)
b = np.linspace(1,2,4)
print(a,b)

[0 1 2 3] [1.         1.33333333 1.66666667 2.        ]


In [399]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [400]:
b += a

In [401]:
print(b)

[1.         2.33333333 3.66666667 5.        ]


Matrix operations

In [538]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[4 5]
 [6 7]]


In [411]:
a + b

array([[ 5,  7],
       [ 9, 11]])

In [412]:
a * b

array([[ 4, 10],
       [18, 28]])

In [413]:
a @ b

array([[16, 19],
       [36, 43]])

In [415]:
a.dot(b)

array([[16, 19],
       [36, 43]])

In [541]:
a.T  # np.transpose(a)

array([[1, 3],
       [2, 4]])

Aggregate functions

In [436]:
a = np.linspace(1,4,9).reshape(3,3)
print(a)

[[1.    1.375 1.75 ]
 [2.125 2.5   2.875]
 [3.25  3.625 4.   ]]


In [437]:
a.min()

1.0

In [438]:
a.max()

4.0

In [439]:
a.argmax()

8

In [440]:
a.argmin()

0

In [441]:
a.mean()

2.5

In [442]:
a.sum()

22.5

In [443]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [444]:
a.sum(axis=0)

array([12, 15, 18])

In [445]:
a.sum(axis=1)

array([ 6, 15, 24])

In [446]:
a.min(axis=0)

array([1, 2, 3])

In [447]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [448]:
a.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [449]:
a.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [459]:
a = np.array([[1,0,0,1],[1,1,0,0]])
b = np.array([1,1,1,1])
print(a)
print()
print(b)

[[1 0 0 1]
 [1 1 0 0]]

[1 1 1 1]


In [455]:
a.any()

True

In [453]:
a.all()

False

In [460]:
b.all()

True

In [461]:
a.any(axis=0)

array([ True,  True, False,  True])

In [462]:
a.any(axis=1)

array([ True,  True])

In [475]:
a.all(axis = 0, keepdims=True)

array([[ True, False, False, False]])

#### Sorting

In [506]:
a = np.array([[1,3,2],[6,2,3]])
print(a)

[[1 3 2]
 [6 2 3]]


In [507]:
a.sort()
a

array([[1, 2, 3],
       [2, 3, 6]])

#### Sorting on structured array

In [525]:
data = [('apple', 'small' , 20),('apple', 'large' , 60),('apple', 'small', 25),('apple', 'large' , 10)]
dt = [('fruit','S10'), ('size','S10'),('price', 'int' )]

In [531]:
fruits = np.array(data, dtype=dt)
print(fruits)

[(b'apple', b'small', 20) (b'apple', b'large', 60)
 (b'apple', b'small', 25) (b'apple', b'large', 10)]


In [535]:
fruits.sort(order=['price'])
print(fruits)

[(b'apple', b'large', 10) (b'apple', b'small', 20)
 (b'apple', b'small', 25) (b'apple', b'large', 60)]


In [537]:
fruits.sort(order = ['size', 'price'])
print(fruits)

[(b'apple', b'large', 10) (b'apple', b'large', 60)
 (b'apple', b'small', 20) (b'apple', b'small', 25)]


#### Indexing, Slicing and Iterating

In [559]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [544]:
a[2]

3

In [545]:
a[2:5]

array([3, 4, 5])

In [547]:
a[2:10:2]

array([3, 5, 7, 9])

In [548]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [560]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [561]:
for i in range(a.size):
    print(a[i])

1
2
3
4
5
6
7
8
9
10


#### Multidimensional Array

In [562]:
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [563]:
a[2,2]

12

In [565]:
a[1]

array([5, 6, 7, 8, 9])

In [566]:
a[:,1]

array([ 1,  6, 11, 16, 21])

In [567]:
a[0:2,1]

array([1, 6])

In [568]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [569]:
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [570]:
for element in a.flat:
    print(element, end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

#### Shape manipulation

In [589]:
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [590]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [591]:
a.shape

(4, 6)

In [600]:
a.size

24

In [596]:
a.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [597]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [598]:
a.resize(8,3)

In [599]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### View and Deep copy

In [603]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [604]:
b = a

In [609]:
b.resize(1,9)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [608]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [619]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [620]:
b = a.view()
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [621]:
b.resize(1,9)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [622]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [623]:
b[0,0] = 200
b

array([[200,   1,   2,   3,   4,   5,   6,   7,   8]])

In [624]:
a

array([[200,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [625]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [627]:
b = a.copy()
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [628]:
b[0,0] = 200
b

array([[200,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [629]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])